stream {
    map $ssl_preread_server_name $quickvpn_stream_backend {
        vpn.netlumavpn.example 127.0.0.1:8443;
        default 127.0.0.1:1443;
    }

    server {
        listen 443;
        listen [::]:443;
        proxy_pass $quickvpn_stream_backend;
        ssl_preread on;
    }
}
